name: Frontend CI

on:
  pull_request:
    paths:
      - "client/**"
  push:
    branches: [main]
    paths:
      - "client/**"

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build
